lsst.daf.butler.cli.utils ERROR: Caught an exception, details are in traceback:
Traceback (most recent call last):
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/ctrl_mpexec/g45d0adf2d3+61755f3ad1/python/lsst/ctrl/mpexec/cli/cmd/commands.py", line 220, in run
    if (qgraph := script.qgraph(pipelineObj=pipeline, **kwargs, show=show)) is None:
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/ctrl_mpexec/g45d0adf2d3+61755f3ad1/python/lsst/ctrl/mpexec/cli/script/qgraph.py", line 196, in qgraph
    qgraph = f.makeGraph(pipelineObj, args)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/ctrl_mpexec/g45d0adf2d3+61755f3ad1/python/lsst/ctrl/mpexec/cmdLineFwk.py", line 586, in makeGraph
    qgraph = graphBuilder.makeGraph(
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/graphBuilder.py", line 1589, in makeGraph
    return scaffolding.makeQuantumGraph(
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/graphBuilder.py", line 1376, in makeQuantumGraph
    qset = task.makeQuantumSet(missing=self.missing, datastore_records=datastore_records)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/graphBuilder.py", line 563, in makeQuantumSet
    raise exc
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/graphBuilder.py", line 543, in makeQuantumSet
    tmpQuanta = q.makeQuantum(datastore_records)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/graphBuilder.py", line 410, in makeQuantum
    helper.adjust_in_place(self.task.taskDef.connections, self.task.taskDef.label, self.dataId)
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/connections.py", line 749, in adjust_in_place
    adjusted_inputs_by_connection, adjusted_outputs_by_connection = connections.adjustQuantum(
  File "/cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2023_19/conda/envs/lsst-scipipe-6.0.0-exact-ext/share/eups/Linux64/pipe_base/g3fc0ca6f3d+10ab99c206/python/lsst/pipe/base/connections.py", line 633, in adjustQuantum
    raise FileNotFoundError(
FileNotFoundError: Not enough datasets (0) found for non-optional connection isr.camera (camera) with minimum=1 for quantum data ID {instrument: 'LSSTCam', detector: 166, exposure: 3021122200421, ...}.
